### ISSUE TITLE
Version 0.1.5 does not allow painting of images

### ISSUE THREAD

**Issue by VisionaryMind** [BlenderHQ/camera_projection_painter#2]
I have been trying to follow your video tutorial, but it looks absolutely nothing like this version here on Github. I do the following:

1. Export FBX from RealityCapture.
2. Import FBX into Blender 2.83.
3. Attempt to locate Camera Painter in Scene Settings, but it is only visible in Tool Settings.
4. Select Source Images directory and click "Bind All Camera Images".
5. Open the Texture section and under Textures, click + to add new Base Color texture.
6. Set texture height and width to 8192, color to black, and uncheck Alpha.
7. Click the Setup Context button. The view changes to Texture Draw with images loaded in cameras.
8. Ensure that the new texture is selected (and the whole mesh is black).
9. Click on camera origin of choice, and select "Set Active". A striped rectangle is now surrounding the projection area.
10. Move brush over the texture / mesh and see that the image is being projected in the brush.
11. Left-mouse click to try to paint with brush and "image-colored" brush freezes, but brush outline remains mobile.
12. Release left mouse button, and nothing is painted.

I have tried every possible combination, CTRL-click, Shift-click..... and even changing the viewport mode to material, texture, vertex. There is absolutely nothing I can do that will allow painting with your tool on a mesh.  Do you have any ideas why this may be happening and if there is any advice how to get a result? We've been struggling with this for nearly a week now with a wide variety of datasets. This tool was the only one that showed any promise, if we could only get it working.

**Comment by ivan-perevala** [comment]
Hi! Sorry, just have seen opened issue.
It looks like you watched one of older videos, here is the last one, it is relative to current Github addon version as well:
https://youtu.be/lasdJIIAv70
I just downloaded Blender version 2.83.9 LTS and cannot reproduce the situation you described with exact the same steps. It is possible that I have different data set for tests.
But I always can provide a support for products I share.

So, may I ask you about some additional information?

- Does regular painting process act? It is quite possible it caused by brush paint settings like zeroed paint offset curve. Please, check this out with same brush and paint settings as in your issued blend file.

- Check out in "Mesh" tab UV map settings. When addon's context is ready to go, you should see the "cpp_data" UV map. You cannot select it, but please, check this out as well.

- Is "Warnings" checkbox active? If you paint high resolution texture, this option should warn you about that the painting process may become extremely slow (it is Blender's known limitation). So, the situation you described is possible if "Warnings" sub-option "Lock Paint" is active but "Brush Preview" - not. Also, in this case anyway you should see warning "Danger zone" in the status bar.

**Comment by VisionaryMind** [comment]
@ivan-perevala 

> Does regular painting process act? It is quite possible it caused by brush paint settings like zeroed paint offset curve. Please, check this out with same brush and paint settings as in your issued blend file.

Both regular and clone texture painting work without a problem. I have over a hundred cameras, so I grew tired of creating a new UV map for each projection. I was hoping your tool could be used instead.

> Check out in "Mesh" tab UV map settings. When addon's context is ready to go, you should see the "cpp_data" UV map. You cannot select it, but please, check this out as well.

Yes, the cpp_data UV map is there, and in the workspace settings panel, I have it set to:

Mode: Single image, UV Map (original map), Linear
Clone from paint slot: Source clone image (for the selected camera), and source clone UV Map set to cpp_data

> Is "Warnings" checkbox active? If you paint high resolution texture, this option should warn you about that the painting process may become extremely slow (it is Blender's known limitation). So, the situation you described is possible if "Warnings" sub-option "Lock Paint" is active but "Brush Preview" - not. Also, in this case anyway you should see warning "Danger zone" in the status bar.

Yes, warnings is checked. I am in texture paint mode, I have selected a camera and set it to active and checked the settings above. But when I hover the brush over the mesh, it does not show a sample of the camera. Now, hopefully this will help --- there _is_ a white boundary for some of the photos, and within that white boundary I can paint.... perhaps 10-12 out out of more than a hundred photos. The remaining photos display properly in camera projection mode, but the white boundaries are either not visible or cut off. Further your tool seems to be chopping off the mesh leaving only 1/4 of it to be painted. In other words, I can see only a small portion of the mesh in the camera. If I create my own UV Map, and "project from bounds" to the camera image, the entire image is mapped to the mesh. In this add-on, however, it cuts out the majority of the mesh from the photo, making it unreachable. 

I am now using 2.9, and the same issues are present there as well. Every mesh, every set of photos -- every time. If you could point me to the portion of code that is chopping off the mesh or putting up "danger" zones --- if I could just remove those, then I would probable be able to paint without a problem. I think the limitations are getting in the way.

**Comment by ivan-perevala** [comment]
@VisionaryMind Yes. that is strange behavior.

>  could just remove those, then I would probable be able to paint without a problem. I think the limitations are getting in the way.
This option can be deactivated by unchecking the "Warnings" flag in UI, you do not need to edit code.

A few days ago I asked a lot of people who using this addon (on Facebook), maybe someone running into it issue, but no one. May I ask you for a quick private discuss on Facebook to speedup process of fixing / describing? For sure, I will leave summarize here as well.
[Contact me](https://www.facebook.com/vanyokperevala)

Currently I preparing addon for cummulative update, so I would to know what happening in more short terms.

**Comment by ivan-perevala** [comment]
@VisionaryMind Yes. that is strange behavior.

>  could just remove those, then I would probable be able to paint without a problem. I think the limitations are getting in the way.
This option can be deactivated by unchecking the "Warnings" flag in UI, you do not need to edit code.

A few days ago I asked a lot of people who using this addon (on Facebook), maybe someone running into it issue, but no one. May I ask you for a quick private discuss on Facebook to speedup process of fixing / describing? For sure, I will leave summarize here as well.
[](url)

Currently I preparing addon for cummulative update, so I would to know what happening in more short terms.

**Comment by ivan-perevala** [comment]
Also, can I ask for a sample of a typical scene you are having problems with, in *,blend or *,fbx format? (you can not use the entire dataset, but leave only 2-3 cameras). With respect to copyright, you can also modify the object, the main thing is that you can recreate the problem from this scene.

**Comment by ivan-perevala** [comment]
I close an issue as invalid, it cannot be reproduced without additional information.
Also I suggest you try it on clear Blender installation, without any other addons and than use the simpliest dataset you have. Feel free to reopen issue if you want.
