### ISSUE TITLE
_engine is not found

### ISSUE THREAD

**Issue by jjhesk** [BlenderHQ/camera_projection_painter#4]
I install the package and the shows the error.

<img width="715" alt="image" src="https://user-images.githubusercontent.com/629338/111176644-7a8c8800-85e4-11eb-9623-39257665f239.png">

**Comment by ivan-perevala** [comment]
@jjhesk, module `camera_projection_painter-master.engine._engine` is a c++ module. It performs the main algorithms of most important operators. Make sure you have Microsoft Visual C++ Redistributable installed.

https://aka.ms/vs/16/release/vc_redist.x64.exe (actual, Microsoft website)
