### ISSUE TITLE
Convert unit of principal point (from pixel to mm w.r.t 35mm film format)

### ISSUE THREAD

**Issue by richard-bmc** [BlenderHQ/camera_projection_painter#5]
Thank you in advance for your great work for this add-on.

I'm trying to import model and camera information from ContextCapture into Blender, and use CPP for painting texture manually. I managed to assign all camera calibration/distortion parameters via script, except principal point.

The unit ContextCapture used for principal point is "image coordinates", while the parameter used in CPP is "mm".The pop-up info for principal point says "Deviation of the camera principal point in millimeters w.r.t 35mm film format". But it seems I failed to convert it right. The photos cannot align with the model perfectly.

The formula I used to convert principal point coordinates is:
px = (px' - cx) * sensor_width / image_width
py = (py' - cy) * sensor_height / image_height
where
(px, py): the coordinates of principal point, unit: mm
(px', py'): the coordinates of principal point in image plane, unit: pixel
(cx, cy): the coordinates of center point in image plane, unit: pixel
unit of sensor_width/sensor_height: mm
unit of image_width/image_height: pixel

How can I convert the coordinates w.r.t 35mm film format? Any advice is appreciated. Thank you!

**Comment by ivan-perevala** [comment]
A long story short, the original evaluation of optical center was made via equation (adopted to your variable naming):
```
scale_to_pixel = max(image_width, image_height); /* Larger side of the image. */
px' = px * scale_to_pixel + (image_width / 2); /* from that simple eq, I think is not a big deal to get 'px' in millimeters from your pixel coordinates. */
py' = py * scale_to_pixel + (image_height / 2);
f' = f * scale_to_pixel / 36.0f; /* Camera focal length w.r.t 35mm film format in pixel coordinates */
```
That was (at most), design question, but I think you should correct your equation due to that. Just keep in mind that sensor always should be 35mm, so the easiest way is corect your focal length (in Blender, of course).

**Comment by ivan-perevala** [comment]
@richard-bmc I hope the information provided in previous post was helpfull. Please, feel free to re-open the issue if you have any questions.

**Comment by richard-bmc** [comment]
@ivan-perevala Although this issue has been closed, but I still want to thank you for your help.
Finally I got it right, it's really not a big deal to get 'px' in millimeters. Your equation helped!

**Comment by ivan-perevala** [comment]
It's really nice to hear!

In fact, I would still recommend reviewing the addon code in terms of the dependence of the ratio of the height and width of the original image and the correction of the width and type of the Blender camera sensor. In this software, this relationship works a little differently than in photo-scan-oriented software.
